language: ruby
rvm:
  - 2.2

before_install:
  - gem update bundler

script:
  - rake build
  - rake test

branches:
  only:
    - draft 

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true   # speeds up installation of html-proofer
